import Head from 'next/head'
import Link from 'next/link'
import { Layout } from '../components/Layout'
import { Banner } from '../components/Banner'
import { Post } from '../components/Post'
import groq from 'groq'
import client from '../../client'

const HomePage = ({ posts }: any) => {
  return (
    <div>
      <Head>
        <title>vitor.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="max-w-3xl mx-auto">
          <Banner />
          <ul className="flex flex-col gap-4 py-4">
            {posts.length > 0 &&
              posts.map((post: any) => (
                <li key={post.slug} className="list-none">
                  <Link href={`/post/${post?.slug?.current}`}>
                    <Post post={post} />
                  </Link>
                </li>
              ))}
          </ul>
        </div>
      </Layout>
    </div>
  )
}

export const getStaticProps = async () => {
  const posts = await client.fetch(groq`
    *[_type == "post" && publishedAt < now()] | order(publishedAt desc){
      title,
      caption,
      "categories": categories[]->title,
      _createdAt,
      readingTime,
      mainImage,
      slug,
    }
  `)

  return {
    props: {
      posts,
    },
  }
}

export default HomePage
