import Head from 'next/head'
import { Layout } from '../components/Layout'
import { Banner } from '../components/Banner'
import { Post } from '../components/Post'

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>vitor.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="max-w-3xl mx-auto">
          <Banner />
          <div className="flex flex-col gap-4 py-4">
            <Post />
            <Post />
            <Post />
            <Post />
          </div>
        </div>
      </Layout>
    </div>
  )
}

export default HomePage
