import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '../../components/Layout'
import { User } from '../../components/User'
import { Tag } from '../../components/Tag'
import { Divider } from '../../components/Divider'
import { About } from '../../components/About'
// import { Post } from '../../components/Post'
import groq from 'groq'
import imageUrlBuilder from '@sanity/image-url'
import client from '../../../client'

function urlFor(source: any) {
  return imageUrlBuilder(client).image(source)
}

const PostPage = ({ post }: any) => {
  const {
    title = 'Missing title',
    name = 'Missing name',
    categories,
    authorImage,
  } = post

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="max-w-3xl mx-auto flex flex-col gap-3 sm:gap-4 py-4 px-4 sm:px-0">
          <div className="flex justify-between flex-wrap gap-4 sm:gap-0">
            <User />
            <ul className="flex gap-2">
              {categories.map((category: string) => (
                <li key={category}>
                  <Tag>{category}</Tag>
                </li>
              ))}
            </ul>
          </div>

          <h2 className="text-xl sm:text-3xl text-gray-900 dark:text-white font-semibold">
            {title}
          </h2>

          <p className="text-gray-700 dark:text-gray-200 sm:text-xl">
            React hooks are a new addition to the react library and has since
            been widely adopted by react developers
          </p>

          <div className="flex gap-4">
            <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-200">
              Posted on 10 Nov 22
            </span>
            <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-200">
              Updated on 10 Nov 22
            </span>
            <span className="text-xs sm:text-sm text-gray-700 dark:text-gray-200">
              5 min read
            </span>
          </div>

          <div className="relative w-full aspect-video">
            <Image
              src="/cover.jpg"
              alt="Imagem de capa"
              fill
              style={{ objectFit: 'cover', borderRadius: '4px' }}
            />
          </div>

          <div className="text-white">Markdown Content</div>

          <Divider>Sobre o autor</Divider>
          <About />
          <Divider>Recomendados</Divider>
          {/* <Post />
          <Post />
          <Post /> */}
        </div>
      </Layout>
    </div>
  )
}

const query = groq`*[_type == "post" && slug.current == $slug][0]{
  title,
  "name": author->name,
  "categories": categories[]->title,
  "authorImage": author->image
}`

export const getStaticPaths = async () => {
  const paths = await client.fetch(
    `*[_type == "post" && defined(slug.current)][].slug.current`
  )

  return {
    paths: paths.map((slug: any) => ({ params: { slug } })),
    fallback: true,
  }
}

export const getStaticProps = async (context: any) => {
  const { slug = '' } = context.params
  const post = await client.fetch(query, { slug })

  return {
    props: {
      post,
    },
  }
}

export default PostPage
